# -*- coding: utf-8 -*-
"""RGB2GRA_image processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_N5dIvn8YYmEWQy1Ws44sU8mJwwa5Oz
"""

img_path="/content/2024_09_27_17_39_IMG_1242.JPG"
img_path

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import cv2

pic=mpimg.imread(img_path)

pic
pic.shape

type(pic)

plt.imshow(pic)

pic[0][0]

pic_cv=cv2.imread(img_path)

cv2.imshow('image',pic_cv)#will work only in local pc

from google.colab.patches import cv_imshow
cv_imshow(pic_cv)

!wget

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img=mpimg.imread('/content/IMG_20240924_113107.jpg')

img

type(img)

img.shape

img_plot=plt.imshow(img)
plt.show()

from PIL import Image

img=Image.open('/content/IMG_20240924_113107.jpg')

img_resized=img.resize((200,200))

img_resized.save('img1.jpg')

img_res=mpimg.imread('/content/img1.jpg')
img_res_plot=plt.imshow(img_res)
plt.show()

img_res.shape

import cv2
img=cv2.imread('/content/IMG_20240924_113107.jpg')

type(img)

img.shape

grayscale_image=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

grayscale_image.shape

type(grayscale_image)

from google.colab.patches import cv2_imshow

cv2_imshow(grayscale_image)

